build:
    nodes:
        tests:
            environment:
                java: 'java-8-oracle'
                timezone: Europe/Paris

            tests:
                override:
                    - command: mvn test
                      coverage:
                        file: 'target/site/jacoco/jacoco.xml'
                        format: 'jacoco'
