name: Publish to Maven Central
on:
  push:
    branches: ['master']
    tags: ['v*']

jobs:
  publish:
    name: Publish version ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set project version to ${{ github.ref_name }}
        env:
          REF_NAME: ${{ github.ref_name }}
        run: mvn versions:set "-DnewVersion=${REF_NAME#v*}"
        if: ${{ github.ref_type == 'tag' }}

      - name: Publish package
        run: mvn --batch-mode clean deploy -P 'release-sign-artifacts'
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
